### PR TITLE
Feature/register form

### PR DESCRIPTION
**Pull request by TebogoMothelo**
## Description
Registration form for new users Validation done with angular validation and bootstrap

Fixes issue #3

## How Has This Been Tested?
Component tested using jasmine and karma

## Checklist:

- [] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by thatguycodes** [comment]
Hi @TebogoMothelo  beautiful code you wrote. I noticed that you mixed up some variable names on the registration.spect.ts file e.g you are testing the password form control but you are conducting the test on an email form control.

**Comment by TebogoMothelo** [comment]
> Hi @TebogoMothelo beautiful code you wrote. I noticed that you mixed up some variable names on the registration.spect.ts file e.g you are testing the password form control but you are conducting the test on an email form control.

Thanks for spotting that. Fixed.

**Review by wiredmartian — CHANGES_REQUESTED** [review]
I don't see any routes in the `app-routing.module.ts` file.

Exactly how is this form supposed to be viewed?

**Comment by TebogoMothelo** [comment]
> I don't see any routes in the `app-routing.module.ts` file.
> 
> Exactly how is this form supposed to be viewed?

I see, go to /register

**Review by wiredmartian — APPROVED** [review]

**Pull request merged**
